server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yycttdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yyct
    password: yyct

mybatis:
  mapper-locations: mapper/*.xml